/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GraphSpotlightPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/graph/GraphIndex.ts
var GraphIndex = class {
  constructor(app) {
    this.app = app;
    this.adjacency = /* @__PURE__ */ new Map();
    this.dirty = true;
  }
  invalidate() {
    this.dirty = true;
  }
  build(highlights) {
    const highlightByPath = /* @__PURE__ */ new Map();
    const connectedByPath = /* @__PURE__ */ new Map();
    const edgeColors = /* @__PURE__ */ new Map();
    for (const highlight of highlights) {
      pushMapValue(highlightByPath, highlight.filePath, highlight);
    }
    if (highlights.length > 0) {
      this.ensureAdjacency();
    }
    for (const highlight of highlights) {
      const connectedPaths = this.adjacency.get(highlight.filePath);
      if (!connectedPaths) continue;
      for (const connectedPath of connectedPaths) {
        pushUniqueHighlight(connectedByPath, connectedPath, highlight);
        pushUniqueColor(edgeColors, edgeKey(highlight.filePath, connectedPath), highlight.color);
      }
    }
    return {
      highlights,
      highlightByPath,
      connectedByPath,
      edgeColors,
      hasHighlights: highlights.length > 0
    };
  }
  ensureAdjacency() {
    if (!this.dirty) return;
    const adjacency = /* @__PURE__ */ new Map();
    const resolvedLinks = this.getResolvedLinks();
    for (const [sourcePath, outgoing] of Object.entries(resolvedLinks)) {
      for (const targetPath of Object.keys(outgoing)) {
        pushAdjacent(adjacency, sourcePath, targetPath);
        pushAdjacent(adjacency, targetPath, sourcePath);
      }
    }
    this.adjacency = adjacency;
    this.dirty = false;
  }
  getResolvedLinks() {
    var _a;
    const cache = this.app.metadataCache;
    return (_a = cache.resolvedLinks) != null ? _a : {};
  }
};
function edgeKey(a, b) {
  return a < b ? `${a}\0${b}` : `${b}\0${a}`;
}
function pushMapValue(map, key, value) {
  const existing = map.get(key);
  if (existing) {
    existing.push(value);
    return;
  }
  map.set(key, [value]);
}
function pushUniqueHighlight(map, key, value) {
  const existing = map.get(key);
  if (existing) {
    if (!existing.some((entry) => entry.id === value.id)) existing.push(value);
    return;
  }
  map.set(key, [value]);
}
function pushUniqueColor(map, key, value) {
  const existing = map.get(key);
  if (existing) {
    if (!existing.includes(value)) existing.push(value);
    return;
  }
  map.set(key, [value]);
}
function pushAdjacent(map, key, value) {
  const existing = map.get(key);
  if (existing) {
    existing.add(value);
    return;
  }
  map.set(key, /* @__PURE__ */ new Set([value]));
}

// src/ui/GraphOverlay.ts
var import_obsidian = require("obsidian");
var GraphOverlay = class {
  constructor(plugin, leaf, hostEl) {
    this.plugin = plugin;
    this.leaf = leaf;
    this.hostEl = hostEl;
    this.suggestions = [];
    this.selectedIndex = 0;
    this.suggestionTimer = null;
    this.suggestionRequestId = 0;
    this.disposers = [];
    this.chipDisposers = [];
    this.suggestionDisposers = [];
    this.hostEl.addClass("graph-spotlight-host");
    this.rootEl = this.hostEl.createDiv({ cls: "graph-spotlight-overlay" });
    this.stackEl = this.rootEl.createDiv({ cls: "graph-spotlight-stack" });
    const barEl = this.stackEl.createDiv({ cls: "graph-spotlight-bar" });
    this.inputEl = barEl.createEl("input", {
      cls: "graph-spotlight-input",
      attr: {
        type: "search",
        placeholder: "Spotlight note...",
        "aria-label": "Search notes to highlight in graph",
        autocomplete: "off",
        spellcheck: "false"
      }
    });
    const clearButton = barEl.createEl("button", {
      cls: "clickable-icon graph-spotlight-icon-button",
      attr: { type: "button", "aria-label": "Clear highlights", title: "Clear highlights" }
    });
    (0, import_obsidian.setIcon)(clearButton, "eraser");
    const menuButton = barEl.createEl("button", {
      cls: "clickable-icon graph-spotlight-icon-button",
      attr: { type: "button", "aria-label": "Highlight options", title: "Highlight options" }
    });
    (0, import_obsidian.setIcon)(menuButton, "more-horizontal");
    this.chipsEl = this.stackEl.createDiv({ cls: "graph-spotlight-chips" });
    this.suggestionsEl = this.rootEl.createDiv({
      cls: "graph-spotlight-suggestions is-hidden",
      attr: { role: "listbox" }
    });
    this.listen(this.inputEl, "input", () => this.scheduleSuggestions());
    this.listen(this.inputEl, "keydown", (event) => this.handleInputKeydown(event));
    this.listen(this.inputEl, "blur", () => {
      window.setTimeout(() => this.hideSuggestions(), 120);
    });
    this.listen(clearButton, "click", () => this.plugin.clearHighlights());
    this.listen(menuButton, "click", (event) => this.openMenu(event));
    this.updateFromSettings();
    this.refresh();
    if (this.plugin.settings.autoFocusSearchOnGraphOpen) {
      window.setTimeout(() => this.inputEl.focus(), 50);
    }
  }
  refresh() {
    this.updateFromSettings();
    this.renderChips(this.plugin.highlights);
    if (this.inputEl.value.trim()) this.scheduleSuggestions(80);
  }
  destroy() {
    if (this.suggestionTimer !== null) window.clearTimeout(this.suggestionTimer);
    disposeAll(this.chipDisposers);
    disposeAll(this.suggestionDisposers);
    for (const dispose of this.disposers.splice(0)) dispose();
    this.rootEl.remove();
    this.hostEl.removeClass("graph-spotlight-host");
  }
  updateFromSettings() {
    this.rootEl.dataset.position = this.plugin.settings.overlayPosition;
    const isBottomPlacement = this.plugin.settings.overlayPosition.startsWith("bottom");
    this.rootEl.dataset.flow = isBottomPlacement ? "up" : "down";
    this.stackEl.dataset.chipPlacement = isBottomPlacement ? "above" : "below";
    this.rootEl.toggleClass("is-hidden", !this.plugin.settings.showSearchBar);
  }
  renderChips(highlights) {
    disposeAll(this.chipDisposers);
    this.chipsEl.empty();
    for (const highlight of highlights) {
      const chipEl = this.chipsEl.createDiv({ cls: "graph-spotlight-chip" });
      chipEl.style.setProperty("--chip-color", highlight.color);
      const removeButton = chipEl.createEl("button", {
        cls: "clickable-icon graph-spotlight-chip-remove",
        attr: {
          type: "button",
          "aria-label": `Remove ${highlight.label}`,
          title: `Remove ${highlight.label}`
        }
      });
      (0, import_obsidian.setIcon)(removeButton, "x");
      this.listen(removeButton, "click", () => this.plugin.removeHighlight(highlight.id), this.chipDisposers);
      chipEl.createSpan({ cls: "graph-spotlight-chip-label", text: highlight.label });
      const colorInput = chipEl.createEl("input", {
        cls: "graph-spotlight-color",
        attr: {
          type: "color",
          value: highlight.color,
          "aria-label": `Color for ${highlight.label}`,
          title: `Color for ${highlight.label}`
        }
      });
      this.listen(colorInput, "input", () => {
        chipEl.style.setProperty("--chip-color", colorInput.value);
        this.plugin.updateHighlightColor(highlight.id, colorInput.value);
      }, this.chipDisposers);
    }
  }
  scheduleSuggestions(delay = 140) {
    if (this.suggestionTimer !== null) window.clearTimeout(this.suggestionTimer);
    const requestId = ++this.suggestionRequestId;
    this.suggestionTimer = window.setTimeout(() => {
      this.suggestionTimer = null;
      this.updateSuggestions(requestId);
    }, delay);
  }
  updateSuggestions(requestId = ++this.suggestionRequestId) {
    const query = this.inputEl.value.trim();
    if (!query) {
      this.hideSuggestions();
      return;
    }
    if (requestId !== this.suggestionRequestId) return;
    this.suggestions = this.plugin.searchFiles(query, this.plugin.settings.suggestionLimit);
    this.selectedIndex = 0;
    this.renderSuggestions();
  }
  renderSuggestions() {
    disposeAll(this.suggestionDisposers);
    this.suggestionsEl.empty();
    this.suggestionsEl.removeClass("is-hidden");
    if (this.suggestions.length === 0) {
      this.suggestionsEl.createDiv({ cls: "graph-spotlight-empty", text: "No notes found" });
      return;
    }
    this.suggestions.forEach((suggestion, index) => {
      const option = this.suggestionsEl.createEl("button", {
        cls: "graph-spotlight-suggestion",
        attr: {
          type: "button",
          role: "option",
          "aria-selected": index === this.selectedIndex ? "true" : "false"
        }
      });
      option.toggleClass("is-selected", index === this.selectedIndex);
      option.createSpan({ cls: "graph-spotlight-suggestion-title", text: suggestion.label });
      option.createSpan({ cls: "graph-spotlight-suggestion-path", text: suggestion.secondary });
      this.listen(option, "mousedown", (event) => event.preventDefault(), this.suggestionDisposers);
      this.listen(option, "click", () => this.addSuggestion(index), this.suggestionDisposers);
    });
  }
  handleInputKeydown(event) {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      this.moveSelection(1);
      return;
    }
    if (event.key === "ArrowUp") {
      event.preventDefault();
      this.moveSelection(-1);
      return;
    }
    if (event.key === "Escape") {
      this.hideSuggestions();
      return;
    }
    if (event.key === "Enter") {
      event.preventDefault();
      if (this.suggestions.length > 0) {
        this.addSuggestion(this.selectedIndex);
        return;
      }
      const exact = this.plugin.findFileBySearch(this.inputEl.value);
      if (exact) {
        this.plugin.addHighlightByPath(exact.path);
        this.inputEl.value = "";
        this.hideSuggestions();
      }
    }
  }
  moveSelection(delta) {
    if (this.suggestions.length === 0) return;
    this.selectedIndex = (this.selectedIndex + delta + this.suggestions.length) % this.suggestions.length;
    this.renderSuggestions();
  }
  addSuggestion(index) {
    const suggestion = this.suggestions[index];
    if (!suggestion) return;
    this.plugin.addHighlightByPath(suggestion.filePath);
    this.inputEl.value = "";
    this.hideSuggestions();
  }
  hideSuggestions() {
    if (this.suggestionTimer !== null) {
      window.clearTimeout(this.suggestionTimer);
      this.suggestionTimer = null;
    }
    this.suggestionRequestId += 1;
    this.suggestions = [];
    this.selectedIndex = 0;
    disposeAll(this.suggestionDisposers);
    this.suggestionsEl.empty();
    this.suggestionsEl.addClass("is-hidden");
  }
  openMenu(event) {
    const menu = new import_obsidian.Menu();
    menu.addItem((item) => {
      item.setTitle("Save current set").setIcon("save").setDisabled(this.plugin.highlights.length === 0).onClick(() => this.plugin.promptSaveCurrentSet());
    });
    menu.addItem((item) => {
      item.setTitle("Clear highlights").setIcon("eraser").setDisabled(this.plugin.highlights.length === 0).onClick(() => this.plugin.clearHighlights());
    });
    if (this.plugin.settings.savedSets.length > 0) {
      menu.addSeparator();
      for (const set of this.plugin.settings.savedSets) {
        menu.addItem((item) => {
          item.setTitle(`Load ${set.name}`).setIcon("folder-open").onClick(() => this.plugin.loadSavedSet(set.id));
        });
      }
    } else {
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("No saved sets").setDisabled(true);
      });
    }
    menu.showAtMouseEvent(event);
  }
  listen(element, type, listener, disposers = this.disposers) {
    element.addEventListener(type, listener);
    disposers.push(() => element.removeEventListener(type, listener));
  }
};
function disposeAll(disposers) {
  for (const dispose of disposers.splice(0)) dispose();
}

// src/utils/colors.ts
var HEX_COLOR = /^#?[0-9a-f]{6}$/i;
function normalizeHexColor(value) {
  const trimmed = value.trim();
  if (!HEX_COLOR.test(trimmed)) return null;
  return `#${trimmed.replace("#", "").toLowerCase()}`;
}
function parseColorPool(value) {
  const parsed = value.split(/[\s,;]+/).map((part) => normalizeHexColor(part)).filter((part) => part !== null);
  return Array.from(new Set(parsed));
}
function hexToRgb(hex) {
  var _a;
  const normalized = (_a = normalizeHexColor(hex)) != null ? _a : "#ffffff";
  const value = Number.parseInt(normalized.slice(1), 16);
  return {
    r: value >> 16 & 255,
    g: value >> 8 & 255,
    b: value & 255
  };
}
function rgbToHex(rgb) {
  const r = clampChannel(rgb.r).toString(16).padStart(2, "0");
  const g = clampChannel(rgb.g).toString(16).padStart(2, "0");
  const b = clampChannel(rgb.b).toString(16).padStart(2, "0");
  return `#${r}${g}${b}`;
}
function hexToPixiRgb(hex) {
  var _a;
  const normalized = (_a = normalizeHexColor(hex)) != null ? _a : "#ffffff";
  return Number.parseInt(normalized.slice(1), 16);
}
function mixHexColors(colors) {
  var _a;
  if (colors.length === 0) return "#ffffff";
  if (colors.length === 1) return (_a = normalizeHexColor(colors[0])) != null ? _a : "#ffffff";
  let x = 0;
  let y = 0;
  let saturation = 0;
  let lightness = 0;
  for (const color of colors) {
    const hsl = rgbToHsl(hexToRgb(color));
    const radians = hsl.h / 360 * Math.PI * 2;
    x += Math.cos(radians) * hsl.s;
    y += Math.sin(radians) * hsl.s;
    saturation += hsl.s;
    lightness += hsl.l;
  }
  const hue = (Math.atan2(y, x) * 180 / Math.PI + 360) % 360;
  const averageSaturation = Math.min(0.96, saturation / colors.length + 0.12);
  const averageLightness = clamp(lightness / colors.length + 0.04, 0.36, 0.68);
  return rgbToHex(hslToRgb({ h: hue, s: averageSaturation, l: averageLightness }));
}
function softenColor(hex, amount) {
  return blendHex(hex, "#8a9099", clamp(amount, 0, 1));
}
function blendHex(a, b, amount) {
  const first = hexToRgb(a);
  const second = hexToRgb(b);
  const t = clamp(amount, 0, 1);
  return rgbToHex({
    r: first.r + (second.r - first.r) * t,
    g: first.g + (second.g - first.g) * t,
    b: first.b + (second.b - first.b) * t
  });
}
function pickVibrantColor(usedColors, pool) {
  const normalizedPool = pool.map((color) => normalizeHexColor(color)).filter((color) => color !== null);
  if (normalizedPool.length === 0) return "#4d96ff";
  const used = new Set(
    usedColors.map((color) => normalizeHexColor(color)).filter((color) => color !== null)
  );
  const unused = normalizedPool.filter((color) => !used.has(color));
  const candidates = unused.length > 0 ? unused : normalizedPool;
  const index = Math.floor(Math.random() * candidates.length);
  return candidates[index];
}
function rgbToHsl(rgb) {
  const r = rgb.r / 255;
  const g = rgb.g / 255;
  const b = rgb.b / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      default:
        h = (r - g) / d + 4;
        break;
    }
    h *= 60;
  }
  return { h, s, l };
}
function hslToRgb(hsl) {
  const h = (hsl.h % 360 + 360) % 360;
  const s = clamp(hsl.s, 0, 1);
  const l = clamp(hsl.l, 0, 1);
  if (s === 0) {
    const value = l * 255;
    return { r: value, g: value, b: value };
  }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const hk = h / 360;
  return {
    r: hueToRgb(p, q, hk + 1 / 3) * 255,
    g: hueToRgb(p, q, hk) * 255,
    b: hueToRgb(p, q, hk - 1 / 3) * 255
  };
}
function hueToRgb(p, q, t) {
  let value = t;
  if (value < 0) value += 1;
  if (value > 1) value -= 1;
  if (value < 1 / 6) return p + (q - p) * 6 * value;
  if (value < 1 / 2) return q;
  if (value < 2 / 3) return p + (q - p) * (2 / 3 - value) * 6;
  return p;
}
function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}
function clampChannel(value) {
  return Math.round(clamp(value, 0, 255));
}

// src/graph/GraphRendererAdapter.ts
var STYLE_CHUNK_SIZE = 100;
var STYLE_CHUNK_BUDGET_MS = 3;
var GraphRendererAdapter = class {
  constructor(app) {
    this.app = app;
    this.originalNodeStyles = /* @__PURE__ */ new WeakMap();
    this.originalLinkStyles = /* @__PURE__ */ new WeakMap();
    this.renderers = /* @__PURE__ */ new Set();
    this.rendererTargets = /* @__PURE__ */ new WeakMap();
    this.pathCache = /* @__PURE__ */ new Map();
    this.pathLookup = /* @__PURE__ */ new Map();
    this.pathLookupDirty = true;
    this.styleRunId = 0;
  }
  applyToOpenGraphs(state, settings, includeLeaf = () => true, requestGraphRender = false) {
    const runId = ++this.styleRunId;
    if (state.hasHighlights) this.ensurePathLookup();
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (!isSupportedGraphLeaf(leaf)) return;
      if (!includeLeaf(leaf)) return;
      const renderer = getRendererFromView(leaf.view);
      if (!renderer) return;
      const target = getGraphContainer(leaf);
      if (target) this.rendererTargets.set(renderer, target);
      this.renderers.add(renderer);
      this.applyRenderer(renderer, state, settings, requestGraphRender, target);
    });
  }
  restoreAll() {
    var _a;
    const runId = ++this.styleRunId;
    for (const renderer of this.renderers) {
      this.restoreRendererChunked(
        renderer,
        objectValues(renderer.nodes),
        [...objectValues(renderer.links), ...objectValues(renderer.edges)],
        runId,
        true,
        (_a = this.rendererTargets.get(renderer)) != null ? _a : null
      );
    }
    this.renderers.clear();
  }
  invalidatePathCache() {
    this.pathLookupDirty = true;
    this.pathCache.clear();
  }
  applyRenderer(renderer, state, settings, shouldRequestRender, repaintTarget) {
    const runId = this.styleRunId;
    const nodes = objectValues(renderer.nodes);
    const links = settings.colorLinks ? [...objectValues(renderer.links), ...objectValues(renderer.edges)] : [];
    if (!state.hasHighlights) {
      this.restoreRendererChunked(renderer, nodes, links, runId, shouldRequestRender, repaintTarget);
      return;
    }
    let nodeIndex = 0;
    let linkIndex = 0;
    let nudgedAfterFirstChunk = false;
    const applyChunk = () => {
      if (runId !== this.styleRunId) return;
      try {
        const deadline = performance.now() + STYLE_CHUNK_BUDGET_MS;
        let processed = 0;
        while (nodeIndex < nodes.length && processed < STYLE_CHUNK_SIZE && performance.now() < deadline) {
          this.applyNodeStyle(nodes[nodeIndex], state, settings);
          nodeIndex += 1;
          processed += 1;
        }
        while (nodeIndex >= nodes.length && linkIndex < links.length && processed < STYLE_CHUNK_SIZE && performance.now() < deadline) {
          this.applyLinkStyle(links[linkIndex], state, settings);
          linkIndex += 1;
          processed += 1;
        }
        if (shouldRequestRender && processed > 0 && !nudgedAfterFirstChunk) {
          nudgedAfterFirstChunk = true;
          nudgeGraphView(repaintTarget);
        }
        if (nodeIndex < nodes.length || linkIndex < links.length) {
          scheduleChunk(applyChunk, shouldRequestRender);
          return;
        }
        if (shouldRequestRender) nudgeGraphView(repaintTarget);
      } catch (error) {
        console.error("Graph Spotlight failed to apply graph colors. Restoring graph.", error);
        this.restoreRendererChunked(renderer, nodes, links, runId, true, repaintTarget);
      }
    };
    scheduleChunk(applyChunk, shouldRequestRender);
  }
  applyNodeStyle(node, state, settings) {
    this.snapshotNode(node);
    const nodePath = this.resolveGraphPath(extractNodePath(node));
    const highlighted = nodePath ? state.highlightByPath.get(nodePath) : void 0;
    const connected = nodePath ? state.connectedByPath.get(nodePath) : void 0;
    if (highlighted && highlighted.length > 0) {
      setNodeColor(node, mixHexColors(highlighted.map((entry) => entry.color)), 1);
      return;
    }
    if (connected && connected.length > 0) {
      const baseColor = mixHexColors(connected.map((entry) => entry.color));
      const softened = softenColor(baseColor, settings.connectedNodeDullness);
      setNodeColor(node, softened, settings.connectedNodeOpacity);
      return;
    }
    if (settings.recolorUnrelated) {
      setNodeColor(node, settings.unrelatedColor, settings.unrelatedNodeOpacity);
    } else {
      this.restoreNode(node);
    }
  }
  applyLinkStyle(link, state, settings) {
    if (!settings.colorLinks) return;
    this.snapshotLink(link);
    const sourcePath = this.resolveGraphPath(extractEndpointPath(link.source));
    const targetPath = this.resolveGraphPath(extractEndpointPath(link.target));
    const colors = sourcePath && targetPath ? state.edgeColors.get(edgeKey(sourcePath, targetPath)) : void 0;
    if (colors && colors.length > 0) {
      setLinkColor(link, mixHexColors(colors), settings.edgeOpacity);
      return;
    }
    if (settings.recolorUnrelated) {
      setLinkColor(link, settings.unrelatedColor, settings.unrelatedLinkOpacity);
    } else {
      this.restoreLink(link);
    }
  }
  restoreRendererChunked(renderer, nodes, links, runId, shouldRequestRender, repaintTarget) {
    let nodeIndex = 0;
    let linkIndex = 0;
    let nudgedAfterFirstChunk = false;
    const restoreChunk = () => {
      if (runId !== this.styleRunId) return;
      const deadline = performance.now() + STYLE_CHUNK_BUDGET_MS;
      let processed = 0;
      while (nodeIndex < nodes.length && processed < STYLE_CHUNK_SIZE && performance.now() < deadline) {
        this.restoreNode(nodes[nodeIndex]);
        nodeIndex += 1;
        processed += 1;
      }
      while (nodeIndex >= nodes.length && linkIndex < links.length && processed < STYLE_CHUNK_SIZE && performance.now() < deadline) {
        this.restoreLink(links[linkIndex]);
        linkIndex += 1;
        processed += 1;
      }
      if (shouldRequestRender && processed > 0 && !nudgedAfterFirstChunk) {
        nudgedAfterFirstChunk = true;
        nudgeGraphView(repaintTarget);
      }
      if (nodeIndex < nodes.length || linkIndex < links.length) {
        scheduleChunk(restoreChunk, shouldRequestRender);
        return;
      }
      if (shouldRequestRender) nudgeGraphView(repaintTarget);
    };
    scheduleChunk(restoreChunk, shouldRequestRender);
  }
  snapshotNode(node) {
    if (this.originalNodeStyles.has(node)) return;
    this.originalNodeStyles.set(node, {
      color: cloneValue(node.color)
    });
  }
  snapshotLink(link) {
    if (this.originalLinkStyles.has(link)) return;
    this.originalLinkStyles.set(link, {
      color: cloneValue(link.color),
      lineColor: cloneValue(link.lineColor)
    });
  }
  restoreNode(node) {
    const original = this.originalNodeStyles.get(node);
    if (!original) return;
    restoreProperty(node, "color", original.color);
  }
  restoreLink(link) {
    const original = this.originalLinkStyles.get(link);
    if (!original) return;
    restoreProperty(link, "color", original.color);
    restoreProperty(link, "lineColor", original.lineColor);
  }
  resolveGraphPath(value) {
    if (!value) return null;
    const cached = this.pathCache.get(value);
    if (cached !== void 0) return cached;
    let resolved = value;
    if (this.app.vault.getAbstractFileByPath(value)) {
      this.pathCache.set(value, value);
      return value;
    }
    const markdownPath = value.endsWith(".md") ? value : `${value}.md`;
    if (this.app.vault.getAbstractFileByPath(markdownPath)) {
      this.pathCache.set(value, markdownPath);
      return markdownPath;
    }
    const normalized = value.replace(/\.md$/i, "").toLowerCase();
    const lookup = this.pathLookup.get(normalized);
    if (lookup) resolved = lookup;
    this.pathCache.set(value, resolved);
    return resolved;
  }
  ensurePathLookup() {
    if (!this.pathLookupDirty) return;
    this.pathLookup.clear();
    for (const file of this.app.vault.getMarkdownFiles()) {
      setUniquePathLookup(this.pathLookup, file.path.toLowerCase(), file.path);
      setUniquePathLookup(this.pathLookup, file.path.replace(/\.md$/i, "").toLowerCase(), file.path);
      setUniquePathLookup(this.pathLookup, file.basename.toLowerCase(), file.path);
    }
    this.pathLookupDirty = false;
  }
};
function isSupportedGraphLeaf(leaf) {
  var _a;
  const view = leaf.view;
  const type = (_a = view == null ? void 0 : view.getViewType) == null ? void 0 : _a.call(view);
  return type === "graph" || type === "localgraph";
}
function graphViewEnabled(leaf, globalEnabled, localEnabled) {
  var _a;
  const view = leaf.view;
  const type = (_a = view == null ? void 0 : view.getViewType) == null ? void 0 : _a.call(view);
  if (type === "graph") return globalEnabled;
  if (type === "localgraph") return localEnabled;
  return false;
}
function getGraphContainer(leaf) {
  var _a, _b, _c;
  const view = leaf.view;
  const container = (_b = (_a = view.contentEl) != null ? _a : view.containerEl) != null ? _b : null;
  if (!container) return null;
  return (_c = container.querySelector(".graph-view")) != null ? _c : container;
}
function getRendererFromView(view) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  return (_i = (_h = (_f = (_d = (_b = view.renderer) != null ? _b : (_a = view.graph) == null ? void 0 : _a.renderer) != null ? _d : (_c = view.localGraph) == null ? void 0 : _c.renderer) != null ? _f : (_e = view.engine) == null ? void 0 : _e.renderer) != null ? _h : (_g = view.dataEngine) == null ? void 0 : _g.renderer) != null ? _i : null;
}
function objectValues(value) {
  if (!value) return [];
  if (Array.isArray(value)) return value.filter(isGraphObject);
  if (value instanceof Map) return Array.from(value.values()).filter(isGraphObject);
  if (value instanceof Set) return Array.from(value.values()).filter(isGraphObject);
  if (isGraphObject(value)) return Object.values(value).filter(isGraphObject);
  return [];
}
function isGraphObject(value) {
  return typeof value === "object" && value !== null;
}
function extractEndpointPath(value) {
  if (typeof value === "string") return normalizeGraphPath(value);
  if (!isGraphObject(value)) return null;
  return extractNodePath(value);
}
function extractNodePath(node) {
  const direct = firstString(
    node.id,
    node.path,
    node.filePath,
    node.file && isGraphObject(node.file) ? node.file.path : null
  );
  if (direct) return normalizeGraphPath(direct);
  const text = node.text;
  if (isGraphObject(text)) {
    const label = firstString(text.text, text._text, text.value);
    if (label) return normalizeGraphPath(label);
  }
  const getDisplayText = node.getDisplayText;
  if (typeof getDisplayText === "function") {
    try {
      const displayText = getDisplayText.call(node);
      if (typeof displayText === "string") return normalizeGraphPath(displayText);
    } catch (e) {
      return null;
    }
  }
  return null;
}
function normalizeGraphPath(value) {
  const trimmed = value.trim();
  if (trimmed.endsWith(".md")) return trimmed;
  return trimmed;
}
function firstString(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.trim().length > 0) return value;
  }
  return null;
}
function setNodeColor(node, hex, alpha) {
  const color = pixiColor(hex, alpha);
  node.color = color;
}
function setLinkColor(link, hex, alpha) {
  const color = pixiColor(hex, alpha);
  if ("lineColor" in link) link.lineColor = color;
  if ("color" in link) link.color = color;
}
function pixiColor(hex, alpha) {
  return { rgb: hexToPixiRgb(hex), a: alpha };
}
function restoreProperty(source, key, value) {
  if (typeof value === "undefined") {
    delete source[key];
    return;
  }
  source[key] = cloneValue(value);
}
function cloneValue(value) {
  if (!value || typeof value !== "object") return value;
  if (Array.isArray(value)) return [...value];
  return { ...value };
}
function nudgeGraphView(target) {
  if (!target) return;
  window.requestAnimationFrame(() => {
    try {
      const targets = getRepaintTargets(target);
      for (const repaintTarget of targets) {
        const rect = repaintTarget.getBoundingClientRect();
        const clientX = rect.left + rect.width / 2;
        const clientY = rect.top + rect.height / 2;
        const eventInit = {
          bubbles: true,
          cancelable: true,
          clientX,
          clientY
        };
        if (typeof PointerEvent !== "undefined") {
          repaintTarget.dispatchEvent(new PointerEvent("pointermove", eventInit));
        }
        repaintTarget.dispatchEvent(new MouseEvent("mousemove", eventInit));
      }
    } catch (e) {
    }
  });
}
function getRepaintTargets(target) {
  const canvas = target.querySelector("canvas");
  if (canvas instanceof HTMLElement && canvas !== target) return [canvas, target];
  return [target];
}
function scheduleChunk(callback, urgent = false) {
  if (urgent) {
    window.requestAnimationFrame(callback);
    return;
  }
  const idleWindow = window;
  if (typeof idleWindow.requestIdleCallback === "function") {
    idleWindow.requestIdleCallback(callback, { timeout: 80 });
    return;
  }
  window.requestAnimationFrame(callback);
}
function setUniquePathLookup(map, key, path) {
  const existing = map.get(key);
  if (existing === void 0) {
    map.set(key, path);
    return;
  }
  if (existing !== path) map.set(key, null);
}

// src/ui/SaveSetModal.ts
var import_obsidian2 = require("obsidian");
var SaveSetModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit, existingName = "") {
    super(app);
    this.onSubmit = onSubmit;
    this.existingName = existingName;
    this.name = "";
    this.name = existingName;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Save highlight set" });
    new import_obsidian2.Setting(contentEl).setName("Name").addText((text) => {
      text.setPlaceholder("Research threads").setValue(this.name).onChange((value) => {
        this.name = value;
      });
      window.setTimeout(() => text.inputEl.focus(), 20);
      text.inputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          this.submit();
        }
      });
    });
    new import_obsidian2.Setting(contentEl).addButton((button) => {
      button.setButtonText("Save").setCta().onClick(() => this.submit());
    }).addButton((button) => {
      button.setButtonText("Cancel").onClick(() => this.close());
    });
  }
  onClose() {
    this.contentEl.empty();
  }
  submit() {
    const trimmed = this.name.trim();
    if (!trimmed) return;
    this.onSubmit(trimmed);
    this.close();
  }
};

// src/ui/SettingsTab.ts
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_VIBRANT_COLORS = [
  "#ff4d6d",
  "#ff8a00",
  "#ffd166",
  "#06d6a0",
  "#00c2ff",
  "#4d96ff",
  "#9b5de5",
  "#f15bb5",
  "#2ec4b6",
  "#b8f35a",
  "#ff5f1f",
  "#00f5d4"
];
var DEFAULT_SETTINGS = {
  showSearchBar: true,
  enableGlobalGraph: true,
  enableLocalGraph: true,
  maxHighlights: 10,
  overlayPosition: "top-left",
  chipPlacement: "below",
  recolorUnrelated: true,
  unrelatedColor: "#8b9098",
  unrelatedNodeOpacity: 1,
  unrelatedLinkOpacity: 0.62,
  colorLinks: false,
  connectedNodeOpacity: 0.86,
  connectedNodeDullness: 0.34,
  edgeOpacity: 0.9,
  suggestionLimit: 8,
  autoFocusSearchOnGraphOpen: false,
  clearOnGraphClose: true,
  clearOnActiveNoteClose: true,
  clearOnActiveNoteChange: false,
  vibrantColors: DEFAULT_VIBRANT_COLORS,
  savedSets: []
};

// src/utils/dom.ts
function createId(prefix) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}
function pluralize(count, singular, plural = `${singular}s`) {
  return `${count} ${count === 1 ? singular : plural}`;
}

// src/ui/SettingsTab.ts
var POSITIONS = {
  "top-left": "Top left",
  "top-center": "Top center",
  "top-right": "Top right",
  "bottom-left": "Bottom left",
  "bottom-center": "Bottom center",
  "bottom-right": "Bottom right"
};
var GraphSpotlightSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Graph Spotlight" });
    new import_obsidian3.Setting(containerEl).setName("Show graph search bar").setDesc("Adds the compact spotlight search overlay to supported graph views.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showSearchBar).onChange(async (value) => {
        this.plugin.settings.showSearchBar = value;
        await this.plugin.saveSettings();
        this.plugin.refreshGraphViews();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Global graph").setDesc("Show the spotlight overlay in the global graph view.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableGlobalGraph).onChange(async (value) => {
        this.plugin.settings.enableGlobalGraph = value;
        await this.plugin.saveSettings();
        this.plugin.resetGraphRendering();
        this.plugin.refreshGraphViews();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Local graph").setDesc("Show the spotlight overlay in local graph views.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableLocalGraph).onChange(async (value) => {
        this.plugin.settings.enableLocalGraph = value;
        await this.plugin.saveSettings();
        this.plugin.resetGraphRendering();
        this.plugin.refreshGraphViews();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Maximum active highlights").setDesc("Defaults to 10, but the internals support larger sets.").addSlider((slider) => {
      slider.setLimits(1, 50, 1).setDynamicTooltip().setValue(this.plugin.settings.maxHighlights).onChange(async (value) => {
        this.plugin.settings.maxHighlights = value;
        if (this.plugin.highlights.length > value) {
          this.plugin.trimHighlights(value);
        }
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Overlay position").addDropdown((dropdown) => {
      for (const [value, label] of Object.entries(POSITIONS)) {
        dropdown.addOption(value, label);
      }
      dropdown.setValue(this.plugin.settings.overlayPosition).onChange(async (value) => {
        this.plugin.settings.overlayPosition = value;
        await this.plugin.saveSettings();
        this.plugin.refreshOverlays();
      });
    });
    containerEl.createEl("h3", { text: "Highlight rendering" });
    new import_obsidian3.Setting(containerEl).setName("Grey unrelated notes").setDesc("When highlights are active, recolor notes outside the highlighted neighborhoods to neutral grey.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.recolorUnrelated).onChange(async (value) => {
        this.plugin.settings.recolorUnrelated = value;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Unrelated grey").setDesc("A middle grey works well on both dark and light Obsidian themes.").addColorPicker((picker) => {
      picker.setValue(this.plugin.settings.unrelatedColor).onChange(async (value) => {
        var _a;
        this.plugin.settings.unrelatedColor = (_a = normalizeHexColor(value)) != null ? _a : this.plugin.settings.unrelatedColor;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Unrelated note visibility").addSlider((slider) => {
      slider.setLimits(0.45, 1, 0.01).setDynamicTooltip().setValue(this.plugin.settings.unrelatedNodeOpacity).onChange(async (value) => {
        this.plugin.settings.unrelatedNodeOpacity = value;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Color graph links").setDesc("Experimental. Leave off if your Obsidian graph renderer behaves badly with link recoloring.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.colorLinks).onChange(async (value) => {
        this.plugin.settings.colorLinks = value;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
        this.display();
      });
    });
    if (this.plugin.settings.colorLinks) {
      new import_obsidian3.Setting(containerEl).setName("Unrelated link visibility").addSlider((slider) => {
        slider.setLimits(0.2, 1, 0.01).setDynamicTooltip().setValue(this.plugin.settings.unrelatedLinkOpacity).onChange(async (value) => {
          this.plugin.settings.unrelatedLinkOpacity = value;
          await this.plugin.saveSettings();
          this.plugin.applyHighlights();
        });
      });
    }
    new import_obsidian3.Setting(containerEl).setName("Connected note opacity").addSlider((slider) => {
      slider.setLimits(0.35, 1, 0.01).setDynamicTooltip().setValue(this.plugin.settings.connectedNodeOpacity).onChange(async (value) => {
        this.plugin.settings.connectedNodeOpacity = value;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Connected note dullness").setDesc("Higher values move connected notes closer to neutral gray.").addSlider((slider) => {
      slider.setLimits(0, 0.8, 0.01).setDynamicTooltip().setValue(this.plugin.settings.connectedNodeDullness).onChange(async (value) => {
        this.plugin.settings.connectedNodeDullness = value;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Highlighted link opacity").setDesc("Used only when graph link coloring is enabled.").addSlider((slider) => {
      slider.setLimits(0.2, 1, 0.01).setDynamicTooltip().setValue(this.plugin.settings.edgeOpacity).onChange(async (value) => {
        this.plugin.settings.edgeOpacity = value;
        await this.plugin.saveSettings();
        this.plugin.applyHighlights();
      });
    });
    containerEl.createEl("h3", { text: "Behavior" });
    new import_obsidian3.Setting(containerEl).setName("Suggestion count").addSlider((slider) => {
      slider.setLimits(3, 20, 1).setDynamicTooltip().setValue(this.plugin.settings.suggestionLimit).onChange(async (value) => {
        this.plugin.settings.suggestionLimit = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Focus search on graph open").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoFocusSearchOnGraphOpen).onChange(async (value) => {
        this.plugin.settings.autoFocusSearchOnGraphOpen = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Clear when graph closes").setDesc("Removes temporary highlights when no supported graph view remains open.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.clearOnGraphClose).onChange(async (value) => {
        this.plugin.settings.clearOnGraphClose = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Clear when active note closes").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.clearOnActiveNoteClose).onChange(async (value) => {
        this.plugin.settings.clearOnActiveNoteClose = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Clear when active note changes").setDesc("Optional stricter mode for local-note workflows.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.clearOnActiveNoteChange).onChange(async (value) => {
        this.plugin.settings.clearOnActiveNoteChange = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Color pool" });
    new import_obsidian3.Setting(containerEl).setName("Vibrant colors").setDesc("Comma, semicolon, or whitespace separated hex colors used for new highlights.").addTextArea((text) => {
      text.inputEl.addClass("graph-spotlight-settings-palette");
      text.setValue(this.plugin.settings.vibrantColors.join(", ")).onChange(async (value) => {
        const colors = parseColorPool(value);
        if (colors.length === 0) return;
        this.plugin.settings.vibrantColors = colors;
        await this.plugin.saveSettings();
      });
    }).addButton((button) => {
      button.setButtonText("Reset").onClick(async () => {
        this.plugin.settings.vibrantColors = [...DEFAULT_VIBRANT_COLORS];
        await this.plugin.saveSettings();
        this.display();
      });
    });
    containerEl.createEl("h3", { text: "Saved sets" });
    this.renderSavedSets(containerEl);
  }
  renderSavedSets(containerEl) {
    if (this.plugin.settings.savedSets.length === 0) {
      containerEl.createDiv({ cls: "setting-item-description", text: "No saved highlight sets yet." });
      return;
    }
    for (const set of this.plugin.settings.savedSets) {
      const row = containerEl.createDiv({ cls: "graph-spotlight-saved-set" });
      const label = row.createDiv();
      label.createDiv({ cls: "graph-spotlight-saved-set-name", text: set.name });
      label.createDiv({
        cls: "graph-spotlight-saved-set-meta",
        text: pluralize(set.highlights.length, "highlight")
      });
      const actions = row.createDiv({ cls: "setting-item-control" });
      new import_obsidian3.Setting(actions).addButton((button) => {
        button.setButtonText("Load").onClick(() => this.plugin.loadSavedSet(set.id));
      }).addButton((button) => {
        button.setButtonText("Delete").setWarning().onClick(async () => {
          this.plugin.settings.savedSets = this.plugin.settings.savedSets.filter((item) => item.id !== set.id);
          await this.plugin.saveSettings();
          new import_obsidian3.Notice(`Deleted ${set.name}`);
          this.display();
        });
      });
    }
  }
};

// src/main.ts
var GraphSpotlightPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS, vibrantColors: [...DEFAULT_SETTINGS.vibrantColors] };
    this.highlights = [];
    this.overlays = /* @__PURE__ */ new Map();
    this.refreshTimer = null;
    this.applyTimer = null;
    this.pendingGraphRenderRequest = false;
    this.lastActiveFilePath = null;
    this.searchRecords = [];
    this.searchIndexDirty = true;
  }
  async onload() {
    await this.loadSettings();
    this.graphIndex = new GraphIndex(this.app);
    this.rendererAdapter = new GraphRendererAdapter(this.app);
    this.addSettingTab(new GraphSpotlightSettingTab(this.app, this));
    this.addCommand({
      id: "clear-graph-spotlights",
      name: "Clear graph spotlights",
      callback: () => this.clearHighlights()
    });
    this.addCommand({
      id: "save-current-graph-spotlights",
      name: "Save current graph spotlight set",
      callback: () => this.promptSaveCurrentSet()
    });
    this.addCommand({
      id: "reload-graph-spotlight-renderer",
      name: "Refresh graph spotlight rendering",
      callback: () => this.refreshGraphViews()
    });
    this.registerEvent(this.app.workspace.on("layout-change", () => this.scheduleRefresh()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.scheduleRefresh()));
    this.registerEvent(this.app.workspace.on("file-open", (file) => this.handleFileOpen(file)));
    this.registerEvent(this.app.vault.on("create", () => this.handleVaultFilesChanged()));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => this.handleRename(file, oldPath)));
    this.registerEvent(this.app.vault.on("delete", (file) => this.handleDelete(file)));
    this.registerEvent(this.app.metadataCache.on("resolved", () => {
      this.graphIndex.invalidate();
      if (this.highlights.length > 0) this.scheduleApplyHighlights(300);
    }));
    this.app.workspace.onLayoutReady(() => this.refreshGraphViews());
  }
  onunload() {
    if (this.refreshTimer !== null) {
      window.clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
    if (this.applyTimer !== null) {
      window.clearTimeout(this.applyTimer);
      this.applyTimer = null;
    }
    for (const overlay of this.overlays.values()) {
      overlay.destroy();
    }
    this.overlays.clear();
    this.rendererAdapter.restoreAll();
  }
  async loadSettings() {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    const loaded = await this.loadData();
    const legacy = loaded;
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...loaded != null ? loaded : {},
      recolorUnrelated: (_b = (_a = legacy == null ? void 0 : legacy.recolorUnrelated) != null ? _a : legacy == null ? void 0 : legacy.dimUnrelated) != null ? _b : DEFAULT_SETTINGS.recolorUnrelated,
      unrelatedColor: (_d = normalizeHexColor((_c = legacy == null ? void 0 : legacy.unrelatedColor) != null ? _c : "")) != null ? _d : DEFAULT_SETTINGS.unrelatedColor,
      unrelatedNodeOpacity: (_f = (_e = legacy == null ? void 0 : legacy.unrelatedNodeOpacity) != null ? _e : legacy == null ? void 0 : legacy.dimOpacity) != null ? _f : DEFAULT_SETTINGS.unrelatedNodeOpacity,
      unrelatedLinkOpacity: (_g = legacy == null ? void 0 : legacy.unrelatedLinkOpacity) != null ? _g : typeof (legacy == null ? void 0 : legacy.dimOpacity) === "number" ? Math.max(0.2, legacy.dimOpacity * 1.8) : DEFAULT_SETTINGS.unrelatedLinkOpacity,
      colorLinks: (_h = loaded == null ? void 0 : loaded.colorLinks) != null ? _h : DEFAULT_SETTINGS.colorLinks,
      vibrantColors: (_i = sanitizeColorPool(loaded == null ? void 0 : loaded.vibrantColors)) != null ? _i : [...DEFAULT_SETTINGS.vibrantColors],
      savedSets: Array.isArray(loaded == null ? void 0 : loaded.savedSets) ? loaded.savedSets : []
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  refreshGraphViews() {
    const seen = /* @__PURE__ */ new Set();
    let supportedGraphCount = 0;
    let createdOverlay = false;
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (!isSupportedGraphLeaf(leaf)) return;
      if (!graphViewEnabled(leaf, this.settings.enableGlobalGraph, this.settings.enableLocalGraph)) return;
      supportedGraphCount += 1;
      seen.add(leaf);
      if (!this.settings.showSearchBar) return;
      if (this.overlays.has(leaf)) return;
      const host = getGraphContainer(leaf);
      if (!host) return;
      this.overlays.set(leaf, new GraphOverlay(this, leaf, host));
      createdOverlay = true;
    });
    for (const [leaf, overlay] of Array.from(this.overlays.entries())) {
      if (!seen.has(leaf) || !this.settings.showSearchBar) {
        overlay.destroy();
        this.overlays.delete(leaf);
      }
    }
    if (supportedGraphCount === 0 && this.settings.clearOnGraphClose && this.highlights.length > 0) {
      this.clearHighlights({ silent: true, skipGraphRefresh: true });
      return;
    }
    this.refreshOverlays();
    if (createdOverlay && this.highlights.length > 0) this.scheduleApplyHighlights(250);
  }
  refreshOverlays() {
    for (const overlay of this.overlays.values()) {
      overlay.refresh();
    }
  }
  resetGraphRendering() {
    this.rendererAdapter.restoreAll();
  }
  applyHighlights(options = true) {
    var _a, _b;
    const normalizedOptions = typeof options === "boolean" ? { refreshOverlays: options, requestGraphRender: false } : options;
    if ((_a = normalizedOptions.refreshOverlays) != null ? _a : true) this.refreshOverlays();
    this.scheduleApplyHighlights(80, (_b = normalizedOptions.requestGraphRender) != null ? _b : false);
  }
  addHighlightByPath(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian4.TFile)) {
      new import_obsidian4.Notice("That note is no longer available.");
      return;
    }
    if (this.highlights.some((highlight) => highlight.filePath === file.path)) {
      new import_obsidian4.Notice(`${file.basename} is already highlighted.`);
      return;
    }
    if (this.highlights.length >= this.settings.maxHighlights) {
      new import_obsidian4.Notice(`Graph Spotlight is limited to ${pluralize(this.settings.maxHighlights, "active highlight")} for now.`);
      return;
    }
    this.highlights = [
      ...this.highlights,
      {
        id: createId("highlight"),
        filePath: file.path,
        label: file.basename,
        color: pickVibrantColor(
          this.highlights.map((highlight) => highlight.color),
          this.settings.vibrantColors
        ),
        createdAt: Date.now()
      }
    ];
    this.applyHighlights({ requestGraphRender: true });
  }
  removeHighlight(id) {
    const next = this.highlights.filter((highlight) => highlight.id !== id);
    if (next.length === this.highlights.length) return;
    this.highlights = next;
    this.applyHighlights({ requestGraphRender: true });
  }
  updateHighlightColor(id, color) {
    const normalized = normalizeHexColor(color);
    if (!normalized) return;
    this.highlights = this.highlights.map(
      (highlight) => highlight.id === id ? { ...highlight, color: normalized } : highlight
    );
    this.applyHighlights({ requestGraphRender: true });
  }
  clearHighlights(options = {}) {
    if (this.highlights.length === 0) return;
    this.highlights = [];
    this.rendererAdapter.applyToOpenGraphs(
      this.graphIndex.build(this.highlights),
      this.getRendererSettings(),
      (leaf) => graphViewEnabled(leaf, this.settings.enableGlobalGraph, this.settings.enableLocalGraph),
      true
    );
    this.refreshOverlays();
    if (!options.silent) new import_obsidian4.Notice("Graph spotlights cleared.");
    if (!options.skipGraphRefresh) this.refreshOverlays();
  }
  trimHighlights(maxHighlights) {
    if (this.highlights.length <= maxHighlights) return;
    this.highlights = this.highlights.slice(0, maxHighlights);
    this.applyHighlights({ requestGraphRender: true });
  }
  promptSaveCurrentSet() {
    if (this.highlights.length === 0) {
      new import_obsidian4.Notice("Add at least one graph spotlight before saving a set.");
      return;
    }
    new SaveSetModal(this.app, (name) => {
      void this.saveCurrentSet(name);
    }).open();
  }
  async saveCurrentSet(name) {
    const normalizedName = name.trim();
    if (!normalizedName) return;
    const now = Date.now();
    const highlights = this.highlights.map((highlight) => ({
      filePath: highlight.filePath,
      label: highlight.label,
      color: highlight.color
    }));
    const existing = this.settings.savedSets.find((set) => set.name.toLowerCase() === normalizedName.toLowerCase());
    if (existing) {
      existing.name = normalizedName;
      existing.updatedAt = now;
      existing.highlights = highlights;
    } else {
      this.settings.savedSets = [
        ...this.settings.savedSets,
        {
          id: createId("set"),
          name: normalizedName,
          createdAt: now,
          updatedAt: now,
          highlights
        }
      ];
    }
    await this.saveSettings();
    new import_obsidian4.Notice(`Saved ${normalizedName}.`);
  }
  loadSavedSet(id) {
    var _a;
    const set = this.settings.savedSets.find((candidate) => candidate.id === id);
    if (!set) return;
    const missing = [];
    const highlights = [];
    for (const saved of set.highlights.slice(0, this.settings.maxHighlights)) {
      const file = this.app.vault.getAbstractFileByPath(saved.filePath);
      if (!(file instanceof import_obsidian4.TFile)) {
        missing.push(saved.label);
        continue;
      }
      highlights.push({
        id: createId("highlight"),
        filePath: file.path,
        label: file.basename,
        color: (_a = normalizeHexColor(saved.color)) != null ? _a : pickVibrantColor([], this.settings.vibrantColors),
        createdAt: Date.now()
      });
    }
    this.highlights = highlights;
    this.applyHighlights({ requestGraphRender: true });
    if (missing.length > 0) {
      new import_obsidian4.Notice(`Loaded ${set.name}; ${pluralize(missing.length, "note")} could not be found.`);
    } else {
      new import_obsidian4.Notice(`Loaded ${set.name}.`);
    }
  }
  searchFiles(query, limit) {
    const normalizedQuery = normalizeSearch(query);
    if (!normalizedQuery) return [];
    return this.getSearchRecords().map((record) => scoreFile(record, normalizedQuery)).filter((suggestion) => suggestion !== null).sort((a, b) => b.score - a.score || a.label.localeCompare(b.label)).slice(0, limit);
  }
  findFileBySearch(query) {
    const normalizedQuery = normalizeSearch(query);
    if (!normalizedQuery) return null;
    const exact = this.getSearchRecords().find((record) => {
      return record.basename === normalizedQuery || record.path === normalizedQuery;
    });
    if (exact) return exact.file;
    const first = this.searchFiles(query, 1).first();
    if (!first) return null;
    const file = this.app.vault.getAbstractFileByPath(first.filePath);
    return file instanceof import_obsidian4.TFile ? file : null;
  }
  scheduleRefresh(delay = 120) {
    if (this.refreshTimer !== null) window.clearTimeout(this.refreshTimer);
    this.refreshTimer = window.setTimeout(() => {
      this.refreshTimer = null;
      this.refreshGraphViews();
    }, delay);
  }
  scheduleApplyHighlights(delay = 80, requestGraphRender = false) {
    this.pendingGraphRenderRequest = this.pendingGraphRenderRequest || requestGraphRender;
    if (this.applyTimer !== null) window.clearTimeout(this.applyTimer);
    const effectiveDelay = requestGraphRender ? 0 : delay;
    this.applyTimer = window.setTimeout(() => {
      this.applyTimer = null;
      const shouldRequestGraphRender = this.pendingGraphRenderRequest;
      this.pendingGraphRenderRequest = false;
      this.applyHighlightsNow(shouldRequestGraphRender);
    }, effectiveDelay);
  }
  applyHighlightsNow(requestGraphRender = false) {
    const state = this.graphIndex.build(this.highlights);
    this.rendererAdapter.applyToOpenGraphs(
      state,
      this.getRendererSettings(),
      (leaf) => graphViewEnabled(leaf, this.settings.enableGlobalGraph, this.settings.enableLocalGraph),
      requestGraphRender
    );
  }
  handleFileOpen(file) {
    var _a;
    const nextPath = (_a = file == null ? void 0 : file.path) != null ? _a : null;
    const previousPath = this.lastActiveFilePath;
    if (!nextPath && previousPath && this.settings.clearOnActiveNoteClose) {
      this.clearHighlights({ silent: true });
    } else if (nextPath && previousPath && nextPath !== previousPath && this.settings.clearOnActiveNoteChange) {
      this.clearHighlights({ silent: true });
    }
    this.lastActiveFilePath = nextPath;
    this.scheduleRefresh(50);
  }
  handleRename(file, oldPath) {
    this.rendererAdapter.invalidatePathCache();
    this.graphIndex.invalidate();
    this.searchIndexDirty = true;
    if (!(file instanceof import_obsidian4.TFile)) return;
    let changed = false;
    this.highlights = this.highlights.map((highlight) => {
      if (highlight.filePath !== oldPath) return highlight;
      changed = true;
      return { ...highlight, filePath: file.path, label: file.basename };
    });
    for (const set of this.settings.savedSets) {
      for (const highlight of set.highlights) {
        if (highlight.filePath === oldPath) {
          highlight.filePath = file.path;
          highlight.label = file.basename;
          set.updatedAt = Date.now();
          changed = true;
        }
      }
    }
    if (changed) {
      void this.saveSettings();
      this.applyHighlights({ requestGraphRender: true });
    }
  }
  handleDelete(file) {
    this.rendererAdapter.invalidatePathCache();
    this.graphIndex.invalidate();
    this.searchIndexDirty = true;
    if (!(file instanceof import_obsidian4.TFile)) return;
    const next = this.highlights.filter((highlight) => highlight.filePath !== file.path);
    if (next.length === this.highlights.length) return;
    this.highlights = next;
    this.applyHighlights({ requestGraphRender: true });
  }
  handleVaultFilesChanged() {
    this.rendererAdapter.invalidatePathCache();
    this.graphIndex.invalidate();
    this.searchIndexDirty = true;
    if (this.highlights.length > 0) this.scheduleApplyHighlights(250);
  }
  getSearchRecords() {
    if (!this.searchIndexDirty) return this.searchRecords;
    this.searchRecords = this.app.vault.getMarkdownFiles().map((file) => ({
      file,
      basename: normalizeSearch(file.basename),
      path: normalizeSearch(file.path)
    }));
    this.searchIndexDirty = false;
    return this.searchRecords;
  }
  getRendererSettings() {
    return {
      recolorUnrelated: this.settings.recolorUnrelated,
      unrelatedColor: this.settings.unrelatedColor,
      unrelatedNodeOpacity: this.settings.unrelatedNodeOpacity,
      unrelatedLinkOpacity: this.settings.unrelatedLinkOpacity,
      colorLinks: this.settings.colorLinks,
      connectedNodeOpacity: this.settings.connectedNodeOpacity,
      connectedNodeDullness: this.settings.connectedNodeDullness,
      edgeOpacity: this.settings.edgeOpacity
    };
  }
};
function sanitizeColorPool(colors) {
  if (!Array.isArray(colors)) return null;
  const normalized = colors.map((color) => normalizeHexColor(color)).filter((color) => color !== null);
  return normalized.length > 0 ? Array.from(new Set(normalized)) : null;
}
function normalizeSearch(value) {
  return value.toLowerCase().trim().replace(/\.md$/, "");
}
function scoreFile(record, query) {
  const { basename, path, file } = record;
  let score = 0;
  if (basename === query) score = 1e3;
  else if (basename.startsWith(query)) score = 850 - basename.length;
  else if (basename.includes(query)) score = 680 - basename.indexOf(query);
  else if (path.includes(query)) score = 480 - path.indexOf(query);
  else {
    const fuzzyScore = fuzzyMatchScore(basename, query);
    if (fuzzyScore > 0) score = fuzzyScore;
  }
  if (score <= 0) return null;
  return {
    filePath: file.path,
    label: file.basename,
    secondary: file.path,
    score
  };
}
function fuzzyMatchScore(value, query) {
  let score = 0;
  let valueIndex = 0;
  let streak = 0;
  for (const char of query) {
    const foundIndex = value.indexOf(char, valueIndex);
    if (foundIndex === -1) return 0;
    streak = foundIndex === valueIndex ? streak + 1 : 0;
    score += 18 + streak * 8 - Math.max(0, foundIndex - valueIndex);
    valueIndex = foundIndex + 1;
  }
  return score;
}
